[package]
name = "generate-schemas"
version.workspace = true
edition.workspace = true

[dependencies]
schemars = "0.8.22"
serde_json.workspace = true
pumpkin-config = { path = "../pumpkin-config", features = ["schemars"] }
